services:
  app:
    # tty: true # colored output
    build: .
    ports:
      - "127.0.0.1:8089:8000"
    volumes:
      - .:/app
      - /home/ente/blog:/app/posts
    environment:
      - GIN_MODE=release
